Sentiment_analysis_of_youtubers/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path('', include('pwa.urls')),
    path('admin/', admin.site.urls),
    path('',include('sentiment.urls')),
    path('users/',include('users.urls')),
    path('about-us/', include('aboutus.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sentiment/urls.py
from django.urls import path  # Importing necessary libraries for urls
from .views import *  # Importing all the views from views.py

app_name = 'sentiment'  # Initializing app name
urlpatterns = [
    path('', HomeView.as_view(), name='home'),  # Connecting the url route to the view with namespace of home
    path('show_emotion/', FormViewEmotion.as_view(), name="show_emotion"),  # Connecting the url route to the view with namespace of show_emotion
    path('show_sentiment/', FormViewSentiment.as_view(), name="show_sentiment"), # Connecting the url route to the view with namespace of show_emotion
    path('show_emotion_result/', show_emotion, name="show_emotion_result"),  # Connecting the url route to the view with namespace of show_emotion_result
    path('show_sentiment_result/', show_sentiment, name="show_sentiment_result"), # Connecting the url route to the view with namespace of show_emotion_result
    path('show_emotion_video/', FormViewVideoEmotion.as_view(), name="show_emotion_video"),  # Connecting the url route to the view with namespace of show_emotion_video
    path('show_sentiment_video/', FormViewVideoSentiment.as_view(), name="show_sentiment_video"), # Connecting the url route to the view with namespace of show_emotion_video
    path('show_emotion_video_result/', show_emotion_video, name="show_emotion_video_result"),  # Connecting the url route to the view with namespace of show_emotion_video_result
    path('show_sentiment_video_result/', show_sentiment_video, name="show_sentiment_video_result"), # Connecting the url route to the view with namespace of show_emotion_video_result
    path('show_emotion_video_comment/', FormCommentViewVideoEmotion.as_view(), name="show_emotion_video_comment"),  # Connecting the url route to the view with namespace of show_emotion_video
    path('show_sentiment_video_comment/', FormCommentViewVideoSentiment.as_view(), name="show_sentiment_video_comment"), # Connecting the url route to the view with namespace of show_emotion_video
    path('show_emotion_video_result_commment/', show_comment_emotion_video, name="show_emotion_video_comment_result"),  # Connecting the url route to the view with namespace of show_emotion_video_result
    path('show_sentiment_video_result_commment/', show_comment_sentiment_video, name="show_sentiment_video_comment_result"), # Connecting the url route to the view with namespace of show_emotion_video_result
]

users/urls.py
from django.urls import path  # Importing necessary libraries for urls
from .views import *  # Importing all the views from views.py


app_name = "users" # Initializing app name
urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),  # Connecting the url route to the view with namespace of register
    path('login/', UserLoginView.as_view(), name="login"),  # Connecting the url route to the view with namespace of login
    path('logout/', UserLogoutView.as_view(), name="logout"),  # Connecting the url route to the view with namespace of logout
]

sentiment/views.py
from typing import Any, AnyStr  # Using to define the type
import requests
from django.contrib import messages  # Importing messages module for showing errors
from django.contrib.auth.decorators import login_required  # Importing decorator for verifying the authenticated user
from django.http import HttpResponseRedirect  # If any error caused it will help to redirect
from django.shortcuts import render  # Jinja template engine will parse the contents using render
from django.urls import reverse  # Used in redirecting
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers
from django.views.generic.base import TemplateView  # Importing template class based views
from .youtube import get_youtube_comment_data, get_clean_data, get_subtitles, get_youtube_data, get_channel_id
from decouple import config
from .api import analyze_emotion
from .sentiments import sentiment_analysis
from .retrieve_data import get_video_id

API = config('API')


@method_decorator(vary_on_headers('User-Agent', 'Cookie'), name='dispatch')
@method_decorator(cache_page(int(60 * .167), cache="cache1"), name='dispatch')
class HomeView(TemplateView):  # Initializing template for template view
    template_name = 'sentiment/index.html'


@method_decorator(vary_on_headers('User-Agent', 'Cookie'), name='dispatch')
@method_decorator(cache_page(int(60 * .167), cache="cache1"), name='dispatch')
class FormViewSentiment(TemplateView):  # Initializing template for template view
    template_name = 'sentiment/sentiment_sentiment_form.html'


@method_decorator(vary_on_headers('User-Agent', 'Cookie'), name='dispatch')
@method_decorator(cache_page(int(60 * .167), cache="cache1"), name='dispatch')
class FormViewVideoSentiment(TemplateView):  # Initializing template for template view
    template_name = 'sentiment/sentiment_form_sentiment_video.html'


@method_decorator(vary_on_headers('User-Agent', 'Cookie'), name='dispatch')
@method_decorator(cache_page(int(60 * .167), cache="cache1"), name='dispatch')
class FormCommentViewVideoSentiment(TemplateView):  # Initializing template for template view
    template_name = 'sentiment/sentiment_form_sentiment_comment_video.html'


@method_decorator(vary_on_headers('User-Agent', 'Cookie'), name='dispatch')
@method_decorator(cache_page(int(60 * .167), cache="cache1"), name='dispatch')
class FormViewEmotion(TemplateView):  # Initializing template for template view
    template_name = 'sentiment/sentiment_emotion_form.html'


@method_decorator(vary_on_headers('User-Agent', 'Cookie'), name='dispatch')
@method_decorator(cache_page(int(60 * .167), cache="cache1"), name='dispatch')
class FormViewVideoEmotion(TemplateView):  # Initializing template for template view
    template_name = 'sentiment/sentiment_form_emotion_video.html'


@method_decorator(vary_on_headers('User-Agent', 'Cookie'), name='dispatch')
@method_decorator(cache_page(int(60 * .167), cache="cache1"), name='dispatch')
class FormCommentViewVideoEmotion(TemplateView):  # Initializing template for template view
    template_name = 'sentiment/sentiment_form_emotion_comment_video.html'


@login_required(login_url='/users/login/')  # Checking if the user is authenticated
def show_emotion(request: AnyStr) -> Any:
    channel_name = request.POST.get('channel name')  # Getting the channel/video id from the form using post method
    publish_date_after = request.POST.get(
        'publish_date_after')  # Getting the publish_date_after from the form using post method
    publish_date_before = request.POST.get(
        'publish_date_before')  # Getting the publish_date_before from the form using post method

    channel_id = get_channel_id(channel_name)

    if channel_id is None:
        messages.error(request,
                       'Sorry channel does not exists')  # adding the errors in messages list which will be shown in message.html template
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion'))

    if publish_date_before is None or publish_date_after is None:
        return HttpResponseRedirect(reverse('sentiment:show_emotion'))

    video_ids = get_youtube_data(channel_id, publish_date_after,
                                 publish_date_before)  # Getting the video ids using get_youtube_data method

    if len(video_ids) == 0:  # Some basic validations
        messages.error(request,
                       'Services are not working properly or invalid data')  # adding the errors in messages list which will be shown in message.html template
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion'))  # Redirecting to form page if there are any errors.

    texts, error_ = get_subtitles(video_ids)  # Getting the subtitles using get_subtitles method
    if texts == '':  # Some basic validations
        messages.error(request,
                       'Please check the subtitles setting of your channel/video')  # adding the errors in messages list which will be shown in message.html template
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion'))  # Redirecting to form page if there are any errors

    if len(error_) > 0:  # Some basic validations
        messages.error(request,
                       error_)  # adding the errors in messages list which will be shown in message.html template

    texts = get_clean_data(texts)  # Getting the cleaned text using get_clean_data method

    emotion_predictions = analyze_emotion(texts)
    emotion_labels = emotion_predictions['emotion_labels']  # getting the labels
    emotion_predictions = emotion_predictions['emotion_predictions']  # getting the probabilities

    context = {  # setting the context with our data
        'labels': emotion_labels,
        'probabilities': emotion_predictions,
    }

    return render(request, 'sentiment/results_emotion.html',
                  context=context)  # rendering template with out data using jinja template engine


@login_required(login_url='/users/login/')  # Checking if the user is authenticated
def show_emotion_video(request: AnyStr) -> Any:
    url = request.POST.get('url')  # Getting the video id from the form using post method
    if url is None:  # Some basic validations
        messages.error(request,
                       'Please check the url you entered')
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion_video'))
    video_ids = get_video_id(url)
    if video_ids is None:  # Some basic validations
        messages.error(request,
                       'Please check the url you entered')
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion_video'))
    video_ids = video_ids.split(' ')  # converting string to list
    texts, error_ = get_subtitles(video_ids)  # Getting the subtitles using get_subtitles method
    if texts == '':  # Some basic validations
        messages.error(request,
                       'Please check the subtitles setting of your channel/video')  # adding the errors in messages list which will be shown in message.html template
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion_video'))  # Redirecting to form page if there are any errors
    if len(error_) > 0:  # Some basic validations
        messages.error(request,
                       error_)  # adding the errors in messages list which will be shown in message.html template

    texts = get_clean_data(texts)  # Getting the cleaned text using get_clean_data method

    emotion_predictions = analyze_emotion(texts)
    emotion_labels = emotion_predictions['emotion_labels']  # getting the labels
    emotion_predictions = emotion_predictions['emotion_predictions']  # getting the probabilities

    context = {  # setting the context with our data
        'labels': emotion_labels,
        'probabilities': emotion_predictions,
    }
    return render(request, 'sentiment/results_emotion.html',
                  context=context)  # rendering template with out data using jinja template engine


@login_required(login_url='/users/login/')  # Checking if the user is authenticated
def show_comment_emotion_video(request: AnyStr) -> Any:
    url = request.POST.get('url')  # Getting the video id from the form using post method
    if url is None:  # Some basic validations
        messages.error(request,
                       'Please check the url you entered')
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion_video_comment'))
    video_ids = get_video_id(url)
    if video_ids is None:  # Some basic validations
        messages.error(request,
                       'Please check the url you entered')
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion_video_comment'))
    texts = get_youtube_comment_data(video_ids)  # Getting the subtitles using get_subtitles method
    if texts == '':  # Some basic validations
        messages.error(request,
                       'Please check whether the comments are disabled. Also, please check the url you entered.')  # adding the errors in messages list which will be shown in message.html template
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion_video_comment'))  # Redirecting to form page if there are any errors

    if not (texts and not texts.isspace()):  # Some basic validations
        messages.error(request,
                       'Please check the comment settings or try after some time')  # adding the errors in messages list which will be shown in message.html template
        return HttpResponseRedirect(
            reverse('sentiment:show_emotion_video_comment'))  # Redirecting to form page if there are any errors.
    emotion_predictions = analyze_emotion(texts)
    emotion_labels = emotion_predictions['emotion_labels']  # getting the labels

templates/sentiment/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <main>
        <!--? slider Area Start -->
        <div class="slider-area ">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height d-flex align-items-center slide-bg">
                    <div class="container">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8">
                                <div class="hero__caption">
                                    <h1 data-animation="fadeInLeft" data-delay=".4s" data-duration="1000ms">Emotions of comments</h1>
                                    <div class="hero__btn" data-animation="fadeInLeft" data-delay=".8s" data-duration="2000ms">
                                        <a href="{% url 'sentiment:show_emotion_video_comment' %}" class="btn hero-btn">Emotion Analysis</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 d-none d-sm-block">
                                <div class="hero__img" data-animation="bounceIn" data-delay=".4s">
                                    <img src="{% static 'assets/img/hero/unnamed.png' %}" alt="" class=" heartbeat">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="single-slider slider-height d-flex align-items-center slide-bg">
                    <div class="container">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8">
                                <div class="hero__caption">
                                    <h1 data-animation="fadeInLeft" data-delay=".4s" data-duration="1000ms">Sentiments of comments</h1>
                                    <div class="hero__btn" data-animation="fadeInLeft" data-delay=".8s" data-duration="2000ms">
                                        <a href="{% url 'sentiment:show_sentiment_video_comment' %}" class="btn hero-btn">Sentiment Analysis</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 d-none d-sm-block">
                                <div class="hero__img" data-animation="bounceIn" data-delay=".4s">
                                    <img src="{% static 'assets/img/hero/unnamed.png' %}" alt="" class=" heartbeat">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="single-slider slider-height d-flex align-items-center slide-bg">
                    <div class="container">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8">
                                <div class="hero__caption">
                                    <h1 data-animation="fadeInLeft" data-delay=".4s" data-duration="1000ms">Emotions of YouTube channel</h1>
                                    <div class="hero__btn" data-animation="fadeInLeft" data-delay=".8s" data-duration="2000ms">
                                        <a href="{% url 'sentiment:show_emotion' %}" class="btn hero-btn">Emotion Analysis</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 d-none d-sm-block">
                                <div class="hero__img" data-animation="bounceIn" data-delay=".4s">
                                    <img src="{% static 'assets/img/hero/unnamed.png' %}" alt="" class=" heartbeat">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Single Slider -->
                <div class="single-slider slider-height d-flex align-items-center slide-bg">
                    <div class="container">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8">
                                <div class="hero__caption">
                                    <h1 data-animation="fadeInLeft" data-delay=".4s" data-duration="2000ms">Sentiments of YouTube channel</h1>
                                    <div class="hero__btn" data-animation="fadeInLeft" data-delay=".8s" data-duration="2000ms">
                                        <a href="{% url 'sentiment:show_sentiment' %}" class="btn hero-btn">Sentiment Analysis</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 d-none d-sm-block">
                                <div class="hero__img" data-animation="bounceIn" data-delay=".4s">
                                    <img src="{% static 'assets/img/hero/unnamed.png' %}" alt="" class="heartbeat">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="video-area">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-lg-12">
                        <div class="video-wrap">
                            <div class="play-btn "><a class="popup-video" href="https://www.youtube.com/watch?v=OR0wfP2FD3c"><i class="fas fa-play"></i></a></div>
                        </div>
                        <div class="video-wrap">
                            <div class="play-btn "><a class="popup-video" href="https://www.youtube.com/watch?v=OR0wfP2FD3c"><i class="fas fa-play"></i></a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

templates/sentiment/sentiment_emotion_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>
        <!-- Hero Area Start-->
        <div class="slider-area ">
            <div class="single-slider slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Know Your Emotion</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'messages.html' %}
        <!-- Hero Area End-->
        <!--================login_part Area =================-->
        <section class="login_part section_padding ">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_text text-center">
                            <div class="login_part_text_iner">
                                <h2>Trying to find emotion of single video</h2>
                                <p>Know your sentiment/emotion of particular video</p>
                                <a href="{% url 'sentiment:show_emotion_video' %}" class="btn_3">Video's Emotion Analysis</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_form">
                            <div class="login_part_form_iner">
                                <h3>
                                    Know your emotion just by providing few details in a particular timeline</h3>
                                <form class="row contact_form" method="post"action="{% url 'sentiment:show_emotion_result' %}">
                                    {% csrf_token %}
                                    {% if form.errors %}
                                    <div id="errors">
                                        <div class="inner">
                                            <p style="color:red">Please correct the errors below</p>
                                            <ul>
                                                {% for field in form %}
                                                {% if field.errors %}
                                                <li>{{ form.label }} : {{ field.errors|striptags }}</li>
                                                {% endif %}
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                {% endif %}
                                    <div class="col-md-12 form-group p_star">
                                        <input type="text" class="form-control" id="channel name" name="channel name" value=""
                                            required placeholder="please entire the channel name">
                                    </div>                                  
                                    <div class="col-md-12 form-group p_star">
                                        <input placeholder="The date after you published your videos" class="form-control" required name="publish_date_after" type="text" onfocus="(this.type='date')" id="publish_date_after">
                                    </div>
                                    <div class="col-md-12 form-group p_star">
                                        <input placeholder="The date before you published your videos" class="form-control" required name="publish_date_before" type="text" onfocus="(this.type='date')" id="publish_date_before">
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <button type="submit" value="submit" class="btn_3">
                                            Know Your Emotion
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/sentiment/sentiment_form_emotion_comment_video.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>
        <!-- Hero Area Start-->
        <div class="slider-area ">
            <div class="single-slider slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Know the emotion of comments for a particular Video</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% include 'messages.html' %}
        <!-- Hero Area End-->
        <!--================login_part Area =================-->
        <section class="login_part section_padding ">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_text text-center">
                            <div class="login_part_text_iner">
                                <h2>Trying to find emotion of channel videos for a particular channel</h2>
                                <p>There are advances being made in science and technology
                                    everyday, and a good example of this is the</p>
                                <a href="{% url 'sentiment:show_emotion' %}" class="btn_3">Channel's Emotion Analysis</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_form">
                            <div class="login_part_form_iner">
                                <h3>
                                    Know the emotion of comments just by providing few details</h3>
                                <form class="row contact_form" method="post" action="{% url 'sentiment:show_emotion_video_comment_result' %}">
                                    {% csrf_token %}
                                    {% if form.errors %}
                                    <div id="errors">
                                        <div class="inner">
                                            <p style="color:red">Please correct the errors below</p>
                                            <ul>
                                                {% for field in form %}
                                                {% if field.errors %}
                                                <li>{{ form.label }} : {{ field.errors|striptags }}</li>
                                                {% endif %}
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                {% endif %}
                                    <div class="col-md-12 form-group p_star">
                                        <input type="url" class="form-control" id="url" name="url" value=""
                                            required placeholder="please enter the url">
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <button type="submit" value="submit" class="btn_3">
                                            Know Your Emotion
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}