Sentiment_analysis_of_youtubers/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path('', include('pwa.urls')),
    path('admin/', admin.site.urls),
    path('',include('sentiment.urls')),
    path('users/',include('users.urls')),
    path('about-us/', include('aboutus.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aboutus/urls.py
from django.urls import path  # Importing necessary libraries for urls
from .views import *  # Importing all the views from views.py

app_name = "aboutus"  # Initializing app name
urlpatterns = [
    path('', AboutUsView.as_view(), name="about"),  # Connecting the url route to the view with namespace of about

]

sentiment/urls.py
from django.urls import path  # Importing necessary libraries for urls
from .views import *  # Importing all the views from views.py

app_name = 'sentiment'  # Initializing app name
urlpatterns = [
    path('', HomeView.as_view(), name='home'),  # Connecting the url route to the view with namespace of home
    path('show_emotion/', FormViewEmotion.as_view(), name="show_emotion"),  # Connecting the url route to the view with namespace of show_emotion
    path('show_sentiment/', FormViewSentiment.as_view(), name="show_sentiment"), # Connecting the url route to the view with namespace of show_emotion
    path('show_emotion_result/', show_emotion, name="show_emotion_result"),  # Connecting the url route to the view with namespace of show_emotion_result
    path('show_sentiment_result/', show_sentiment, name="show_sentiment_result"), # Connecting the url route to the view with namespace of show_emotion_result
    path('show_emotion_video/', FormViewVideoEmotion.as_view(), name="show_emotion_video"),  # Connecting the url route to the view with namespace of show_emotion_video
    path('show_sentiment_video/', FormViewVideoSentiment.as_view(), name="show_sentiment_video"), # Connecting the url route to the view with namespace of show_emotion_video
    path('show_emotion_video_result/', show_emotion_video, name="show_emotion_video_result"),  # Connecting the url route to the view with namespace of show_emotion_video_result
    path('show_sentiment_video_result/', show_sentiment_video, name="show_sentiment_video_result"), # Connecting the url route to the view with namespace of show_emotion_video_result
    path('show_emotion_video_comment/', FormCommentViewVideoEmotion.as_view(), name="show_emotion_video_comment"),  # Connecting the url route to the view with namespace of show_emotion_video
    path('show_sentiment_video_comment/', FormCommentViewVideoSentiment.as_view(), name="show_sentiment_video_comment"), # Connecting the url route to the view with namespace of show_emotion_video
    path('show_emotion_video_result_commment/', show_comment_emotion_video, name="show_emotion_video_comment_result"),  # Connecting the url route to the view with namespace of show_emotion_video_result
    path('show_sentiment_video_result_commment/', show_comment_sentiment_video, name="show_sentiment_video_comment_result"), # Connecting the url route to the view with namespace of show_emotion_video_result
]

users/urls.py
from django.urls import path  # Importing necessary libraries for urls
from .views import *  # Importing all the views from views.py


app_name = "users" # Initializing app name
urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),  # Connecting the url route to the view with namespace of register
    path('login/', UserLoginView.as_view(), name="login"),  # Connecting the url route to the view with namespace of login
    path('logout/', UserLogoutView.as_view(), name="logout"),  # Connecting the url route to the view with namespace of logout
]

templates/base.html
{% load static %}
{% load pwa %}
<!doctype html>
<html class="no-js' %}" lang="zxx">
<head>
    {% progressive_web_app_meta %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>YouTubers Sentiment</title>
    <meta name="description" content="This app is about helping the youtubers to know about their channel to learn lot more about it">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/img/hero/unnamed.png' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/webfonts/fa-solid-900.woff2">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>


<body>
    <!--? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static '/assets/img/hero/unnamed.png' %}"  alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header header-sticky">
                <div class="container-fluid">
                    <div class="menu-wrapper">
                        <!-- Logo -->
                        <div class="logo">
                            <a href="{% url 'sentiment:home' %}"><img src="{% static '/assets/img/hero/YouTuber_Sentiment.png' %}" class="mt-1"  width="235" height="69" alt="logo"></a>
                        </div>
                        <!-- Main-menu -->
                        <div class="main-menu d-none d-md-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="{% url 'sentiment:home' %}"><span>Home</span></a></li>
                                    <li class="dropdown" data-toggle="dropdown"><a href="#"><span>Types of Analysis</span></a></li>
                                     <div class="dropdown-menu">
                                       <a class="dropdown-item" href="{% url 'sentiment:show_emotion' %}">Emotion Analysis</a>
                                       <a class="dropdown-item" href="{% url 'sentiment:show_emotion_video' %}">Emotion Analysis of video</a>
                                       <a class="dropdown-item" href="{% url 'sentiment:show_emotion_video_comment' %}">Emotion Analysis of video comments</a>
                                       <a class="dropdown-item" href="{% url 'sentiment:show_sentiment' %}">Sentiment Analysis</a>
                                       <a class="dropdown-item" href="{% url 'sentiment:show_sentiment_video' %}">Sentiment Analysis of video</a>
                                       <a class="dropdown-item" href="{% url 'sentiment:show_sentiment_video_comment' %}">Sentiment Analysis of video comments</a>
                                    </div>
                                    <li><a href="{% url 'aboutus:about' %}"><span>About Us</span></a></li>
                                    {% if user.is_authenticated %}
                                    <li> <a href="#"><span>Hi {{user.username}}</span></a></li>
                                    <li><a href="{% url 'users:logout' %}"><span class="flaticon-logout">Logout</span></a> </li>
                                    {% else %}
                                    <li> <a href="{% url 'users:login' %}"><span class="">Login</span></a></li>
                                    <li><a href="{% url 'users:register' %}"><span class="flaticon-register">SignUp</span></a> </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

    {% block content %}

    {% endblock %}
    <footer>
        <!-- Footer Start-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo">
                                    <a href="index.html"><img src="{% static '/assets/img/hero/YouTuber_Sentiment.png' %}" width="275" height="85" alt="logo"></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>We build new technologies to make life more easier and want to bring the youtubers more close to their subscribers</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-3 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <ul>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Quick Links</h4>
                                <ul>
                                    <li><a href="{% url 'sentiment:home' %}">Home</a></li>
                                    <li><a href="{% url 'sentiment:show_emotion' %}">Emotion Analysis</a></li>
                                    <li><a href="{% url 'sentiment:show_emotion_video' %}">Emotion Analysis of video</a></li>
                                    <li><a href="{% url 'sentiment:show_emotion_video_comment' %}">Emotion Analysis of video comments</span></a></li>
                                    <li><a href="{% url 'sentiment:show_sentiment' %}">Sentiment Analysis</a></li>
                                    <li><a href="{% url 'sentiment:show_sentiment_video' %}">Sentiment Analysis of video</a></li>
                                    <li><a href="{% url 'sentiment:show_sentiment_video_comment' %}">Sentiment Analysis of video comments</span></a></li>
                                    <li><a href="{% url 'aboutus:about' %}">About Us</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Footer bottom -->
                <div class="row align-items-center">
                    <div class="col-xl-5 col-lg-4 col-md-5">
                        <div class="footer-copy-right f-right">
                            <!-- social -->
                            <div class="footer-social">
                                <a href="https://twitter.com/DineshNariani"><i class="fab fa-twitter"></i></a>
                                <a href="https://github.com/dineshssdn-867"><i class="fab fa-github"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!--? Search model Begin -->
    <div class="search-model-box">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-btn">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Searching key.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- JS here -->
    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static './assets/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>

    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>
</body>
</html>

templates/messages.html
{% if messages %}

    {% for message in messages %}
<div class="alert alert-danger alert-dismissible text-md-left">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {{ message }}
    </div>
    {% endfor %}

{% endif %}